---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bsk-os
description: Hardened COSMIC computer for BSK.

base-image: ghcr.io/secureblue/cosmic-main-hardened
image-version: 43

modules:
  - type: files
    files:
      - usr: /usr
      - etc: /etc

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-43/atim-starship-fedora-43.repo
    install:
      - micro
      - starship
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user
        install: []

  - type: signing
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-bsk
