# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bsk-os
description: Hardened COSMIC computer for BSK.

base-image: ghcr.io/secureblue/cosmic-main-hardened
image-version: 43

modules:
  - type: files
    files:
      # Existing firewall configs
      - etc/firewalld/zones/bsk-aggressive.xml: /etc/firewalld/zones/bsk-aggressive.xml
      - etc/firewalld/firewalld.conf: /etc/firewalld/firewalld.conf
      - etc/systemd/system-preset/99-bsk-firewalld.preset: /etc/systemd/system-preset/99-bsk-firewalld.preset
      
      # Gatekeeper System Files
      - usr/bin/bsk-gatekeeper.sh: /usr/bin/bsk-gatekeeper.sh
      - etc/systemd/system/bsk-gatekeeper.service: /etc/systemd/system/bsk-gatekeeper.service
      - etc/systemd/system-preset/00-bsk-gatekeeper.preset: /etc/systemd/system-preset/00-bsk-gatekeeper.preset

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org
    install:
      - micro
      - starship
      - firewalld
      - openssl   # Required for integrity check

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - org.gnome.Loupe
      - scope: user
        install: []
