---
# yaml-language-server: $schema=https://schema.blue-build.org
name: bsk-os
description: Hardened COSMIC computer for BSK.
base-image: ghcr.io/secureblue/cosmic-main-hardened
image-version: 43

modules:
  - type: files
    files:
      - etc/firewalld/zones/bsk-aggressive.xml: /etc/firewalld/zones/bsk-aggressive.xml
      - etc/firewalld/firewalld.conf: /etc/firewalld/firewalld.conf
      - etc/systemd/system-preset/99-bsk-firewalld.preset: /etc/systemd/system-preset/99-bsk-firewalld.preset

  - type: dnf
    # Switching to 'packages' and ensuring it is a list of strings
    packages:
      - micro
      - firewalld
      - starship
    # Moving repos to their own specialized module if dnf continues to fail
    # or using the simplest valid repo format:
    repos:
      - https://copr.fedorainfracloud.org

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - org.gnome.Loupe
