# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bsk-os
description: Hardened COSMIC computer for BSK.

base-image: ghcr.io/secureblue/cosmic-main-hardened
image-version: 43

modules:
  - type: files
    files:
      # Existing firewall configs
      - etc/firewalld/zones/bsk-aggressive.xml: /etc/firewalld/zones/bsk-aggressive.xml
      - etc/firewalld/firewalld.conf: /etc/firewalld/firewalld.conf
      - etc/systemd/system-preset/99-bsk-firewalld.preset: /etc/systemd/system-preset/99-bsk-firewalld.preset
      
   - type: dnf
    repos:
      copr:
        - name: atim/starship # Example: owner/project format
        - name: varlad/micro   # Use the specific project name
        
    install:
      - micro
      - starship
      - firewalld


  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - org.gnome.Loupe
      - scope: user
        install: []
