---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bsk-os
description: Hardened COSMIC computer for BSK.

base-image: ghcr.io/secureblue/cosmic-main-hardened
image-version: 43

modules:
  - type: files
    files:
      # This explicitly tells the builder where to map your branding files
      - usr: /usr
      - etc: /etc

  - type: rpm-ostree
    repos:
      # Use the single, full URL for the Starship COPR repo
      - https://copr.fedorainfracloud.org
    install:
      # Use a list of packages directly, without the "packages:" keyword
      - micro
      - starship
    remove:
      # Use a list of packages directly, without the "packages:" keyword
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user

  - type: signing
